[default]
src = 'src'
out = 'artifacts'
libs = [
    'lib',
    'node_modules',
]
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@thirdweb-dev/=node_modules/@thirdweb-dev/',
    'erc721a/=node_modules/erc721a/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config